### ISSUE TITLE
List Python3 requirement in README

### ISSUE THREAD

**Issue by nytyp** [FThompson/BBCSoundDownloader#1]
Runtime error I'm encountering. Does this require a specific python version? I'm on 2.7.10

> ➜  BBCSoundDownloader-master python download.py
> Traceback (most recent call last):
>   File "download.py", line 3, in <module>
>     import urllib.request
> ImportError: No module named request

**Comment by nytyp** [comment]
Update: this appears to run fun in python3. Would be good to add that version requirement to the README, but regardless, thanks so much for making this script!

**Comment by FThompson** [comment]
Added usage instructions to README.
