### ISSUE TITLE
How large is the entire sounds library?

### ISSUE THREAD

**Issue by FThompson** [FThompson/BBCSoundDownloader#4]
If anyone downloads the entire library, please update this issue with the total size of the files downloaded.

**Comment by harakiwi** [comment]
a post on reddit states ~500GB

Post: https://www.reddit.com/r/DataHoarder/comments/a4eyrz/i_wrote_a_script_to_download_bbcs_sound_effects/

**Comment by FThompson** [comment]
> a post on reddit states ~500GB
> 
> Post: https://www.reddit.com/r/DataHoarder/comments/a4eyrz/i_wrote_a_script_to_download_bbcs_sound_effects/

That's my post and my estimate based off of extrapolation from a few hundred samples downloaded. Hopefully someone over there can answer this question!

**Comment by willemcvu** [comment]
The total size is actually only 284GB:
![image](https://user-images.githubusercontent.com/32114876/49716149-d7887f00-fc20-11e8-99d5-a78ecdd05d28.png)
