### ISSUE TITLE
urlopen error retrieval incomplete crash

### ISSUE THREAD

**Issue by kotajacob** [FThompson/BBCSoundDownloader#6]
The script made it most of the way through the download, but failed towards the end. Here's a screenshot. I know it sucks I didn't have time to copy it. https://ptpb.pw/pcP3.png

It looks like the files were being throttled somehow? This was being downloaded with a Gbit connection in London onto an SSD. Using the default of 10 simultaneous connections. It looks like the thing that actually crashed the script was a type error when attempting to show the error reports.

My plan is to try again, but ditch the seemingly buggy urllib feature of python and replace it with an external call to wget. Slightly less slick, but much more well tested and stable. Additionally I'll be saving partial files in the case of a crash again and I think I will rate limit the download.

The plan is to reupload a torrent of the full collection onto archive.org when completed.

**Comment by FThompson** [comment]
Looks like I simply didn't catch that error since I never ran the script to completion, oops.

**Comment by FThompson** [comment]
Fixed the TypeError in commit d1852db to fix the crash at script conclusion but I don't believe this would fix the errors where the files only download partially. Did any files download successfully or did they all encounter this error?

**Comment by kotajacob** [comment]
Awesome I'll mark this as closed, also I see that a user got it up on archive.org which is awesome so I think I may use that torrent to get the collection.
