### ISSUE TITLE
Links to torrent file/magnet link for whole dump

### ISSUE THREAD

**Issue by willemcvu** [FThompson/BBCSoundDownloader#7]
Here's a torrent file: https://archive.org/details/BBCSoundEffectsComplete

And here's the equivelent magnet link: 

`magnet:?xt=urn:btih:277UI76DIYAAPS2LQC3R3XF4PXCS5X5H&dn=BBCSoundEffectsComplete`

**Comment by FThompson** [comment]
Looks great, thanks for doing this!

**Comment by FThompson** [comment]
Added these links to project README.

**Comment by willemcvu** [comment]
Sorry, just FYI I can't really seed it until Thursday morning EST. I had to take that machine down because I needed it with me for somewhere where I don't have gigabit. Sorry again, but I will be seeding it again Thursday morning EST.
